config/routes.rb
Rails.application.routes.draw do
  get 'customers/index'
  get 'customers/alphabetized'
  get 'customers/missing_email'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

end
# Rails.application.routes.draw do
#   resources :customers do
#     collection do
#       get 'alphabetized'
#       get 'missing_email'
#     end
#   end

#   root 'customers#index'
# end
# Rails.application.routes.draw do
#   devise_for :admin_users, ActiveAdmin::Devise.config
#   ActiveAdmin.routes(self)

#   resources :customers do
#     collection do
#       get 'alphabetized'
#       get 'missing_email'
#     end
#   end

#   root 'customers#index'
# end

# Rails.application.routes.draw do
#   devise_for :admin_users, ActiveAdmin::Devise.config
#   ActiveAdmin.routes(self)

#   namespace :api do
#     resources :customers do
#       collection do
#         get 'alphabetized'
#         get 'missing_email'
#       end
#     end
#   end

#   root 'customers#index'
# end


Rails.application.routes.draw do
  resources :customers do
    collection do
      get 'alphabetized'
      get 'missing_email'
    end
  end

  root 'customers#index'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "email", "encrypted_password", "id", "id_value", "remember_created_at", "reset_password_sent_at", "reset_password_token", "updated_at"]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_one_attached :image
  def self.ransackable_attributes(auth_object = nil)
    %w[full_name phone_number email_address notes]
  end
  validates :full_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def index
  end

  def alphabetized
  end

  def missing_email
  end

  def index
    @customers = Customer.all
  end

  def alphabetized
    @customers = Customer.order(:full_name)
  end

  def missing_email
    @customers = Customer.where(email_address: [nil, ''])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_customer.html.erb
<div class="customer">
  <%= image_tag customer.image %>
  <h3><%= customer.full_name %></h3>
  <p><%= customer.phone_number %></p>
  <p><%= customer.email_address %></p>
  <p><%= customer.notes %></p>
</div>

app/views/customers/alphabetized.html.erb
<h1>Customers Alphabetized</h1>

<div class="alphabetized-cards">
  <% @customers.each do |customer| %>
    <%= render partial: 'customer', locals: { customer: customer } %>
  <% end %>
</div>

app/views/customers/index.html.erb
<h1>All Customers</h1>
<div>
  <p><%= link_to "Missing Email Customers", missing_email_customers_path %></p>
  <p><%= link_to "Alphabetized Customers", alphabetized_customers_path %></p>
</div>
<div class="customer-cards" >
  <% @customers.each do |customer| %>
    <%= render partial: 'customer', locals: { customer: customer } %>
  <% end %>
</div>

app/views/customers/missing_email.html.erb
<h1>Customers Missing Email</h1>

<div class="missing_email-cards">
  <% @customers.each do |customer| %>
    <%= render partial: 'customer', locals: { customer: customer } %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>